### PR TITLE
Fuzzy

### PR DESCRIPTION
**Pull request by LinguList**
@tarotis and @xrotwang, I have fixed lingpy and uploaded version 2.6.10 now to PyPi, so we can now integrate the fuzzy reconstruction code into lingrex. My PR provides 100% test coverage, and the code is very short. But I thought it is anyway good if you quickly have a look at it. The whole design may also have to be revised, or certain handling of exceptions etc. is also debatable and can surely be optimized (e.g., calling main class, which now checks for strings, wordlists, and dictionaries).

### CODE REVIEW

**Comment by LinguList** [comment]
With the fuzzy code being added, we may want to think about adding it to our references section in the README as well, the paper.

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
@LinguList should I make a release?

**Comment by LinguList** [comment]
Yes!

**Comment by LinguList** [comment]
@xrotwang, there are two points I'd like to address, but only in documentation. I'd just submit these to master, if this is okay?

**Comment by xrotwang** [comment]
yes, go ahead.

**Pull request merged**
